# Generated by Django 6.0.3 on 2026-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated/')),
                ('room_type', models.CharField(max_length=50)),
                ('lighting', models.CharField(max_length=50)),
                ('person_present', models.BooleanField(default=False)),
            ],
        ),
    ]
